// test/widget_test.dart
//
// Smoke test — verifies that the SocialNetworkApp root class is exported
// from lib/main.dart. Full app widget tests requiring Firebase belong in
// integration_test/; screen-level widget tests live in
// test/features/auth/presentation/widgets/.

import 'package:flutter_test/flutter_test.dart';
import 'package:social_network/main.dart';

void main() {
  test('SocialNetworkApp widget class is exported from main.dart', () {
    // Verifies the class is importable. Replaces the stale MyApp
    // smoke test generated by `flutter create` — MyApp no longer exists.
    expect(SocialNetworkApp, isNotNull);
  });
}
