// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9gYLhzisPGfmIOx9fwOS5Vj_8tm2FFP8',
    appId: '1:521176907703:web:9ae4bcd8a42d6a93753232',
    messagingSenderId: '521176907703',
    projectId: 'localplayers-50b13',
    authDomain: 'localplayers-50b13.firebaseapp.com',
    storageBucket: 'localplayers-50b13.firebasestorage.app',
    measurementId: 'G-9V9SHB8S9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtTVfg2Z7WNXihzbH39cm3Gn9gyYuwfJo',
    appId: '1:521176907703:android:b290d8541bdf28a1753232',
    messagingSenderId: '521176907703',
    projectId: 'localplayers-50b13',
    storageBucket: 'localplayers-50b13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApd7gRrc5Et1Oujjs_LdbLzR-jOd8pfNU',
    appId: '1:521176907703:ios:2a10a87485245655753232',
    messagingSenderId: '521176907703',
    projectId: 'localplayers-50b13',
    storageBucket: 'localplayers-50b13.firebasestorage.app',
    iosBundleId: 'com.example.socialNetwork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApd7gRrc5Et1Oujjs_LdbLzR-jOd8pfNU',
    appId: '1:521176907703:ios:2a10a87485245655753232',
    messagingSenderId: '521176907703',
    projectId: 'localplayers-50b13',
    storageBucket: 'localplayers-50b13.firebasestorage.app',
    iosBundleId: 'com.example.socialNetwork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9gYLhzisPGfmIOx9fwOS5Vj_8tm2FFP8',
    appId: '1:521176907703:web:35cbce5b2f010b00753232',
    messagingSenderId: '521176907703',
    projectId: 'localplayers-50b13',
    authDomain: 'localplayers-50b13.firebaseapp.com',
    storageBucket: 'localplayers-50b13.firebasestorage.app',
    measurementId: 'G-382JS8PW74',
  );
}
