// lib/main.dart
//
// Application entry point — initialises Firebase and wires BLoC + router.
//
// NOTE: This file imports lib/firebase/firebase_options.dart which must be
// generated by running `flutterfire configure` (Firebase Agent responsibility).
// The app will not compile until that file exists.

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import 'package:social_network/core/router/app_router.dart';
import 'package:social_network/features/auth/data/datasources/auth_remote_data_source.dart';
import 'package:social_network/features/auth/data/repositories/auth_repository_impl.dart';
import 'package:social_network/features/auth/domain/repositories/auth_repository.dart';
import 'package:social_network/features/auth/presentation/bloc/auth_bloc.dart';
import 'package:social_network/features/auth/presentation/bloc/auth_event.dart';
import 'package:social_network/features/profile/data/datasources/profile_auth_service.dart';
import 'package:social_network/features/profile/data/datasources/profile_firestore_service.dart';
import 'package:social_network/features/profile/data/datasources/profile_remote_data_source.dart';
import 'package:social_network/features/profile/data/datasources/profile_storage_service.dart';
import 'package:social_network/features/posts/data/repositories/post_repository_impl.dart';
import 'package:social_network/features/posts/domain/repositories/post_repository.dart';
import 'package:social_network/features/posts/presentation/bloc/post_bloc.dart';
import 'package:social_network/features/profile/data/repositories/profile_repository_impl.dart';
import 'package:social_network/features/profile/domain/repositories/profile_repository.dart';
import 'package:social_network/features/profile/presentation/bloc/profile_bloc.dart';
import 'package:social_network/features/follow/data/repositories/follow_repository_impl.dart';
import 'package:social_network/features/follow/domain/repositories/follow_repository.dart';
import 'package:social_network/features/follow/presentation/bloc/follow_bloc.dart';
import 'package:social_network/features/search/presentation/bloc/search_bloc.dart';
import 'package:social_network/firebase_options.dart';

/// Application entry point.
///
/// Initialises Firebase before the widget tree is created, then mounts
/// [SocialNetworkApp] which provides [AuthBloc], [ProfileBloc], and
/// [GoRouter] to the tree.
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const SocialNetworkApp());
}

/// Root widget that constructs and provides [AuthBloc], [ProfileBloc], and
/// [GoRouter].
class SocialNetworkApp extends StatefulWidget {
  /// Creates a [SocialNetworkApp].
  const SocialNetworkApp({super.key});

  @override
  State<SocialNetworkApp> createState() => _SocialNetworkAppState();
}

class _SocialNetworkAppState extends State<SocialNetworkApp> {
  late final AuthRepository _authRepository;
  late final ProfileRepository _profileRepository;
  late final PostRepository _postRepository;
  late final FollowRepository _followRepository;
  late final AuthBloc _authBloc;
  late final ProfileBloc _profileBloc;
  late final PostBloc _postBloc;
  late final FollowBloc _followBloc;
  late final SearchBloc _searchBloc;
  late final GoRouter _router;

  @override
  void initState() {
    super.initState();
    _authRepository = AuthRepositoryImpl(
      dataSource: AuthRemoteDataSource(
        firebaseAuth: FirebaseAuth.instance,
        firestore: FirebaseFirestore.instance,
      ),
    );
    _profileRepository = ProfileRepositoryImpl(
      dataSource: ProfileRemoteDataSource(
        firestoreService: FirebaseProfileFirestoreService(
          FirebaseFirestore.instance,
        ),
        storageService: FirebaseProfileStorageService(
          FirebaseStorage.instance,
        ),
        authService: FirebaseProfileAuthService(FirebaseAuth.instance),
      ),
    );
    _postRepository = PostRepositoryImpl(
      firestore: FirebaseFirestore.instance,
      storage: FirebaseStorage.instance,
    );
    _authBloc = AuthBloc(authRepository: _authRepository)
      ..add(const AuthStarted());
    _profileBloc = ProfileBloc(profileRepository: _profileRepository);
    _postBloc = PostBloc(postRepository: _postRepository);
    _followRepository = FollowRepositoryImpl(
      firestore: FirebaseFirestore.instance,
    );
    _followBloc = FollowBloc(followRepository: _followRepository);
    _searchBloc = SearchBloc(profileRepository: _profileRepository);
    _router = createRouter(authRepository: _authRepository);
  }

  @override
  void dispose() {
    _authBloc.close();
    _profileBloc.close();
    _postBloc.close();
    _followBloc.close();
    _searchBloc.close();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MultiRepositoryProvider(
      providers: [
        RepositoryProvider<ProfileRepository>.value(value: _profileRepository),
        RepositoryProvider<FollowRepository>.value(value: _followRepository),
      ],
      child: MultiBlocProvider(
        providers: [
          BlocProvider<AuthBloc>.value(value: _authBloc),
          BlocProvider<ProfileBloc>.value(value: _profileBloc),
          BlocProvider<PostBloc>.value(value: _postBloc),
          BlocProvider<FollowBloc>.value(value: _followBloc),
          BlocProvider<SearchBloc>.value(value: _searchBloc),
        ],
        child: MaterialApp.router(
          title: 'Social Network',
          theme: ThemeData(
            colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
          ),
          routerConfig: _router,
        ),
      ),
    );
  }
}
